# Generated by Django 4.1.3 on 2022-12-06 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseNames",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("UniversityId", models.IntegerField()),
                ("CourseName", models.CharField(max_length=200)),
                ("CourseId", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Universitieslist",
            fields=[
                (
                    "UniversityId",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("UniversityName", models.CharField(max_length=150)),
                ("StateName", models.CharField(max_length=50)),
                ("StateId", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Subjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CourseId", models.CharField(max_length=10)),
                ("MajorName", models.CharField(max_length=200)),
                (
                    "UniversityId",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.universitieslist",
                    ),
                ),
            ],
        ),
    ]
